### PR TITLE
Add region in KeystoneV3Authenticator credentials.

### PR DESCRIPTION
**Pull request by ghost**
Make code fully compatible with OVH could by adding a region parameter to the  KeystoneV3Authenticator credentials.

exemple : 
  let credentials = {
        "endpointUrl": "https://auth.cloud.ovh.net/v3/",
        "username": config.ovh.osUserName,  
        "password": config.ovh.password,
        "domainId": 'default',
        "region": 'GRA5',
        "projectId": config.ovh.tenantId
      }
  let client = new SwiftClient(new SwiftClient.KeystoneV3Authenticator(credentials));    
  console.log(await client.info());

  // conntected on GRA5

### CODE REVIEW

**Comment by MisterEffix** [comment]
Could you merge this pull request, please.  I have to make an online demo of my app soon.

**Comment by PhilThurston** [comment]
This isn't needed though. If you just exclude the region the OVH auth servers just connect you to the right region automatically with the current version of this project. You're using the words "fully compatible" what exactly isn't working without the region? I could maybe test on my end.

**Comment by MisterEffix** [comment]
If it's possible to connect to the right region with your current version,
could you make a small sample ?

It would be helpfull for me.

FX

**Comment by wassafr** [comment]
I confirm this PR is needed.

Without the region parameter we are connected to the "uk" region, maybe it's the default region for OVH.

I was able to make it work with [another library](https://github.com/matsune/Swift) that exposed the stockage URL and then remplace "storage.uk.cloud.ovh.net" with "storage.<myregion>.cloud.ovh.net". But this is a dirty hack and the library is not maintained anymore so I would prefer stick to this one.

**Comment by wassafr** [comment]
This confirmed for this library as well:

```javascript
client.info().then((data, err) => {
  console.log(data.container_sync.realms.OVH_PUBLIC_CLOUD, err);
});
```

Result:

```
{
  clusters: {
    'SERCO-DIAS1': {},
    DE: {},
    SBG: {},
    UK: { current: true },
    GRA: {},
    WAW: {},
    BHS: {}
  }
}
```

**Comment by stefanodefaria** [comment]
@MisterEffix please resolve conflicts and I'll merge the PR.

**Comment by stefanodefaria** [comment]
Also, please update readme.md with new field in the credentials object.

**Comment by stefanodefaria** [comment]
This feature has been merged as part of #21.

**Pull request closed without merging**
